"""api/_yt_channels.json is generated by design/yt_channels.py from ff-jarvis; it is never hand-written.

2026-10-05. The committed file must equal what the script writes now, so a new channel or an
embed change in ff-jarvis shows up here as a failure until the script is rerun and committed."""
import importlib.util
import json
import pathlib

import pytest

REPO = pathlib.Path(__file__).resolve().parent.parent
COMMITTED = REPO / "api" / "_yt_channels.json"
CODES = ("ARI ATL BAL BUF CAR CHI CIN CLE DAL DEN DET GB HOU IND JAX KC LA LAC LV MIA MIN NE NO NYG NYJ "
         "PHI PIT SEA SF TB TEN WAS").split()


def load_script():
    spec = importlib.util.spec_from_file_location("yt_channels_script", REPO / "design" / "yt_channels.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_the_committed_file_is_what_the_script_writes():
    script = load_script()
    if not (script.CLIENTS / "youtube_channels.json").exists():
        pytest.skip("no ff-jarvis checkout here")
    # git's autocrlf may check the file out with CRLF; the content is what must match.
    assert COMMITTED.read_text(encoding="utf-8").replace("\r\n", "\n") == script.from_ff_jarvis()


def test_every_team_and_the_nfl_is_present():
    table = json.loads(COMMITTED.read_text(encoding="utf-8"))
    assert "NFL" in table
    assert set(table) == set(CODES) | {"NFL"}
    for code, row in table.items():
        assert set(row) == {"uploads", "embed"}, code
        assert row["uploads"].startswith("UU") and len(row["uploads"]) == 24, code
        assert isinstance(row["embed"], bool), code


def test_table_derives_the_uploads_playlist_and_the_embed_flag():
    script = load_script()
    table = script.table({"SEA": "UCabc", "NFL": "UCxyz"}, {"blocked": ["NFL"]})
    assert table == {"NFL": {"uploads": "UUxyz", "embed": False}, "SEA": {"uploads": "UUabc", "embed": True}}


def test_a_non_channel_id_is_refused():
    with pytest.raises(ValueError):
        load_script().table({"SEA": "PLabc"}, {})
